Pull Request for TSE Review: Responsive Design (The Next Web)
Calvinoea/Responsive-Design-The-Next-Web pull request #1
Opened 2020-02-24 15:09 UTC by Calvinoea

Hello,

I am making a request for TSE review of my work for the responsive design project which required a responsive clone to be made of The Next Web (https://thenextweb.com/).

The clone has been made using HTML and CSS. Media queries have been used to make the site responsive. HTML validator (https://validator.w3.org/#validate_by_upload) and stickler have been used to check for errors in the code. Please find below a link to the live demo:

Live Demo
I was given the go-ahead by Microverse to complete the project on my own after my partner had to leave the programme.

Thank you.

2020-02-26 08:06 UTC, addod19 requested changes
## Status: Require changes

Hi @Calvinoea and @Mupa1, your project looks great 👍 good job 🙂 . However, we need to make a few changes to get the project approved. Find comments below:
- ```In medium``` and ```Small screen, ``` There is a horizontal scroll. Kindly fix it to make the project more responsive
- Kindly remove the commented code. ```Line 29``` of ```index.html```
- The 3 articles need some fixing. Kindly increase the width of the leftmost article. 
![res4](https://user-images.githubusercontent.com/46388113/75321580-f183a100-5868-11ea-9670-7bd00d5c6d54.PNG)
Currently, this is what we have
![res3](https://user-images.githubusercontent.com/46388113/75321435-b2555000-5868-11ea-9230-beafba70d7dc.PNG)
```Original version```
![res2](https://user-images.githubusercontent.com/46388113/75321460-bed9a880-5868-11ea-9233-bab49bc439a1.PNG)
- Currently, this is how the 3 articles section looks like on ```Medium screen```
![res6](https://user-images.githubusercontent.com/46388113/75321742-53440b00-5869-11ea-8870-6a3ed381b2ff.PNG)
```Original version``` This is how it should look. With the TNW logo disappearing.
![res5](https://user-images.githubusercontent.com/46388113/75321789-6e167f80-5869-11ea-8baf-a6e22cea4465.PNG)
- ```In the latest news section``` the articles are arranged in 3 articles per row. Currently, we do not have it. 
![res7](https://user-images.githubusercontent.com/46388113/75322229-3fe56f80-586a-11ea-8194-44192bdec570.PNG)
```Original version``` for reference
![res8](https://user-images.githubusercontent.com/46388113/75322263-4c69c800-586a-11ea-90ad-402dee0a551d.PNG)
```In smaller version``` of ```latest news``` currently is not looking good. It aligns 1 article per row. Each article having a cover image on the left and title on the right. This is how it looks currently
![res9](https://user-images.githubusercontent.com/46388113/75322566-e7fb3880-586a-11ea-9a3e-1ca2f6fe67db.PNG)
```Original version``` for reference
![res10](https://user-images.githubusercontent.com/46388113/75322593-f5182780-586a-11ea-9f78-aee5bfcd8e57.PNG)
- ```Latest funding section``` let us fix the header of latest funding on ```medium screens```. The header is overlapping with some texts
![res11](https://user-images.githubusercontent.com/46388113/75322903-a4ed9500-586b-11ea-88e8-cc19e4313c93.PNG)
- Let us fix the latest funding section on small screen. Let us increase the width of the article and the positions of the text. Check images for reference below:
**Currently**
![res12](https://user-images.githubusercontent.com/46388113/75323059-031a7800-586c-11ea-99c1-85bac4f246f7.PNG)
**Original**
![res13](https://user-images.githubusercontent.com/46388113/75323076-0ca3e000-586c-11ea-96f9-877d4f865ea3.PNG)
- Currently, in the ```medium screen``` of the apps, gear, etc. We need some fixing there. This is how it currently looks like
![res14](https://user-images.githubusercontent.com/46388113/75323286-78864880-586c-11ea-9e4a-89daeb993259.PNG)
**Original**
![res15](https://user-images.githubusercontent.com/46388113/75323304-820fb080-586c-11ea-9f80-ef39d836980d.PNG)
- ```The latest deals``` align 3 deals per row. Currently, it looks a bit messy
![res16](https://user-images.githubusercontent.com/46388113/75323694-488b7500-586d-11ea-8463-8f42ba66f43d.PNG)
```Original version```
![res17](https://user-images.githubusercontent.com/46388113/75323713-54773700-586d-11ea-96e4-1abcf7bf145a.PNG)
- The latest deals look messy on small screens.
![res18](https://user-images.githubusercontent.com/46388113/75323877-aae47580-586d-11ea-9735-6070fce58149.PNG)
```Original```
![res19](https://user-images.githubusercontent.com/46388113/75323893-b5067400-586d-11ea-9655-d043083bc768.PNG)
Kindly fix the footer part of the project on a small screen and check the position of the TNW logo on medium screen
Currently
![foo1](https://user-images.githubusercontent.com/46388113/75324364-b3897b80-586e-11ea-9ebf-f23a5bd61534.PNG)
Original
![foo](https://user-images.githubusercontent.com/46388113/75324380-bdab7a00-586e-11ea-8bd0-6f8c2a5cd2fd.PNG)

Make these changes and submit code review 👍 
Happy coding 💻 
Daniel Larbi Addo

2020-02-26 08:21 UTC, addod19 commented
Kindly fix the warning returned by w3validator

2020-02-26 08:32 UTC, Calvinoea commented
> ## Status: Require changes
> Hi @Calvinoea and @Mupa1, your project looks great 👍 good job 🙂 . However, we need to make a few changes to get the project approved. Find comments below:
> 
> * `In medium` and `Small screen, ` There is a horizontal scroll. Kindly fix it to make the project more responsive
> * Kindly remove the commented code. `Line 29` of `index.html`
> * The 3 articles need some fixing. Kindly increase the width of the leftmost article.
>   ![res4](https://user-images.githubusercontent.com/46388113/75321580-f183a100-5868-11ea-9670-7bd00d5c6d54.PNG)
>   Currently, this is what we have
>   ![res3](https://user-images.githubusercontent.com/46388113/75321435-b2555000-5868-11ea-9230-beafba70d7dc.PNG)
>   `Original version`
>   ![res2](https://user-images.githubusercontent.com/46388113/75321460-bed9a880-5868-11ea-9233-bab49bc439a1.PNG)
> * Currently, this is how the 3 articles section looks like on `Medium screen`
>   ![res6](https://user-images.githubusercontent.com/46388113/75321742-53440b00-5869-11ea-8870-6a3ed381b2ff.PNG)
>   `Original version` This is how it should look. With the TNW logo disappearing.
>   ![res5](https://user-images.githubusercontent.com/46388113/75321789-6e167f80-5869-11ea-8baf-a6e22cea4465.PNG)
> * `In the latest news section` the articles are arranged in 3 articles per row. Currently, we do not have it.
>   ![res7](https://user-images.githubusercontent.com/46388113/75322229-3fe56f80-586a-11ea-8194-44192bdec570.PNG)
>   `Original version` for reference
>   ![res8](https://user-images.githubusercontent.com/46388113/75322263-4c69c800-586a-11ea-90ad-402dee0a551d.PNG)
>   `In smaller version` of `latest news` currently is not looking good. It aligns 1 article per row. Each article having a cover image on the left and title on the right. This is how it looks currently
>   ![res9](https://user-images.githubusercontent.com/46388113/75322566-e7fb3880-586a-11ea-9a3e-1ca2f6fe67db.PNG)
>   `Original version` for reference
>   ![res10](https://user-images.githubusercontent.com/46388113/75322593-f5182780-586a-11ea-9f78-aee5bfcd8e57.PNG)
> * `Latest funding section` let us fix the header of latest funding on `medium screens`. The header is overlapping with some texts
>   ![res11](https://user-images.githubusercontent.com/46388113/75322903-a4ed9500-586b-11ea-88e8-cc19e4313c93.PNG)
> * Let us fix the latest funding section on small screen. Let us increase the width of the article and the positions of the text. Check images for reference below:
>   **Currently**
>   ![res12](https://user-images.githubusercontent.com/46388113/75323059-031a7800-586c-11ea-99c1-85bac4f246f7.PNG)
>   **Original**
>   ![res13](https://user-images.githubusercontent.com/46388113/75323076-0ca3e000-586c-11ea-96f9-877d4f865ea3.PNG)
> * Currently, in the `medium screen` of the apps, gear, etc. We need some fixing there. This is how it currently looks like
>   ![res14](https://user-images.githubusercontent.com/46388113/75323286-78864880-586c-11ea-9e4a-89daeb993259.PNG)
>   **Original**
>   ![res15](https://user-images.githubusercontent.com/46388113/75323304-820fb080-586c-11ea-9f80-ef39d836980d.PNG)
> * `The latest deals` align 3 deals per row. Currently, it looks a bit messy
>   ![res16](https://user-images.githubusercontent.com/46388113/75323694-488b7500-586d-11ea-8463-8f42ba66f43d.PNG)
>   `Original version`
>   ![res17](https://user-images.githubusercontent.com/46388113/75323713-54773700-586d-11ea-96e4-1abcf7bf145a.PNG)
> * The latest deals look messy on small screens.
>   ![res18](https://user-images.githubusercontent.com/46388113/75323877-aae47580-586d-11ea-9735-6070fce58149.PNG)
>   `Original`
>   ![res19](https://user-images.githubusercontent.com/46388113/75323893-b5067400-586d-11ea-9655-d043083bc768.PNG)
>   Kindly fix the footer part of the project on a small screen and check the position of the TNW logo on medium screen
>   Currently
>   ![foo1](https://user-images.githubusercontent.com/46388113/75324364-b3897b80-586e-11ea-9ebf-f23a5bd61534.PNG)
>   Original
>   ![foo](https://user-images.githubusercontent.com/46388113/75324380-bdab7a00-586e-11ea-8bd0-6f8c2a5cd2fd.PNG)
> 
> Make these changes and submit code review 👍
> Happy coding 💻
> Daniel Larbi Addo

Hi Daniel. Thank you for your review. The changes will be made as discussed.

2020-02-28 13:03 UTC, uryelah commented
### Code under review by Sarah Chamorro (TSE)

2020-02-28 13:47 UTC, uryelah commented
Hello **Giancarlo Dumani Stradtmann** & **Alvaro Paz Rosero**, I'm Sarah, your reviewer for this PR . 😃 👋 

First of all, you did a great fixing the **Latest news** section on small screens.🕺 

--- 
**Great job for:**

- Use of gradients over images
- Use of semantic HTML
- Attention to text color and font
- Use of icons
-------

###  Requesting changes 🔧 🏗 

You've missed some of the other fixes required by the previous review though:

- [ ] In medium and Small screen, There is a horizontal scroll. Kindly fix it to make the project more responsive (TIP: check [similar issues on stackoverflow](https://stackoverflow.com/questions/25206243/debugging-css-page-overflow) and the `overflow` propriety)

- [ ] Don't keep commented code in your files. Please remove the commented code at the style.css file (line 14 - 41)

- [ ] The TWN logo from the first image disappears in the medium size screens (around 100px width)
Your version:
![Screenshot_2020-02-28 The Next Web](https://user-images.githubusercontent.com/16193212/75552011-22540980-5a14-11ea-900a-cf4c571dacd3.png)
Original page:
![Screenshot_2020-02-28 TNW - International technology news, business and culture](https://user-images.githubusercontent.com/16193212/75552001-1ff1af80-5a14-11ea-8968-864a11113548.png)

- [ ] Good try with the 3 articles but now they left ones are too small. Compare your version and the original one.
![Screenshot_2020-02-28 The Next Web(1)](https://user-images.githubusercontent.com/16193212/75552229-9e4e5180-5a14-11ea-9747-a1240a5e27d3.png)
![Screenshot_2020-02-28 TNW - International technology news, business and culture(1)](https://user-images.githubusercontent.com/16193212/75552234-a0b0ab80-5a14-11ea-95a1-0718222cbb73.png)

- [ ] Nice fix for the  **Latest funding** section for medium screens, but now the text is not properly vertically aligned in small screens (< 700px).

![Screenshot_2020-02-28 The Next Web(2)](https://user-images.githubusercontent.com/16193212/75552506-351b0e00-5a15-11ea-8829-756e9ea387f9.png)

- [ ] There is some unwanted between *Launch* and *Distract* on big screen sizes. Please fix it so they are aligned with the section above.

![Screenshot_2020-02-28 The Next Web(7)](https://user-images.githubusercontent.com/16193212/75553421-1fa6e380-5a17-11ea-92e4-bf82b45579aa.png)


- [ ] Currently, in the medium screen of the apps, gear, etc. (Please refer to the previous review)

![Screenshot_2020-02-28 The Next Web(3)](https://user-images.githubusercontent.com/16193212/75552623-757a8c00-5a15-11ea-9eef-0efaf3ce86c4.png)

- [ ] The latest deals align with 3 deals per row on medium screens and 1 per row on small screens. (Please refer to the last code review)
Your version:
![Screenshot_2020-02-28 The Next Web(4)](https://user-images.githubusercontent.com/16193212/75552759-c38f8f80-5a15-11ea-843a-7423e6ad1992.png)

![Screenshot_2020-02-28 The Next Web(5)](https://user-images.githubusercontent.com/16193212/75552836-f043a700-5a15-11ea-92bf-89ff598ce6a6.png)

Original site:
![Screenshot_2020-02-28 TNW - International technology news, business and culture(3)](https://user-images.githubusercontent.com/16193212/75552900-149f8380-5a16-11ea-9434-fe4f688b909e.png)
![Screenshot_2020-02-28 TNW - International technology news, business and culture(2)](https://user-images.githubusercontent.com/16193212/75552904-1701dd80-5a16-11ea-95c5-b1f79847cfde.png)

- [ ] On scroll some of your page text is overlapping with the fixed navbar. Please fix it's  `z-index`.
![Screenshot_2020-02-28 The Next Web(6)](https://user-images.githubusercontent.com/16193212/75553053-69db9500-5a16-11ea-957e-067cf52f1a68.png)

---

This project is one of the most demanding ones in the HTML path, in my personal opinion, so it's ok to take a bit more time with it. Try to rethink how you are organizing some of your HTML as it can help with positioning and responsibility.

**Please kindly fix the REQUIRED above issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-02-28 14:11 UTC, Calvinoea commented
> Hello **Giancarlo Dumani Stradtmann** & **Alvaro Paz Rosero**, I'm Sarah, your reviewer for this PR . 😃 👋
> 
> First of all, you did a great fixing the **Latest news** section on small screens.🕺
> 
> **Great job for:**
> 
> * Use of gradients over images
> * Use of semantic HTML
> * Attention to text color and font
> * Use of icons
> 
> ### Requesting changes 🔧 🏗
> You've missed some of the other fixes required by the previous review though:
> 
> * [ ]  In medium and Small screen, There is a horizontal scroll. Kindly fix it to make the project more responsive (TIP: check [similar issues on stackoverflow](https://stackoverflow.com/questions/25206243/debugging-css-page-overflow) and the `overflow` propriety)
> * [ ]  Don't keep commented code in your files. Please remove the commented code at the style.css file (line 14 - 41)
> * [ ]  The TWN logo from the first image disappears in the medium size screens (around 100px width)
>   Your version:
>   ![Screenshot_2020-02-28 The Next Web](https://user-images.githubusercontent.com/16193212/75552011-22540980-5a14-11ea-900a-cf4c571dacd3.png)
>   Original page:
>   ![Screenshot_2020-02-28 TNW - International technology news, business and culture](https://user-images.githubusercontent.com/16193212/75552001-1ff1af80-5a14-11ea-8968-864a11113548.png)
> * [ ]  Good try with the 3 articles but now they left ones are too small. Compare your version and the original one.
>   ![Screenshot_2020-02-28 The Next Web(1)](https://user-images.githubusercontent.com/16193212/75552229-9e4e5180-5a14-11ea-9747-a1240a5e27d3.png)
>   ![Screenshot_2020-02-28 TNW - International technology news, business and culture(1)](https://user-images.githubusercontent.com/16193212/75552234-a0b0ab80-5a14-11ea-95a1-0718222cbb73.png)
> * [ ]  Nice fix for the  **Latest funding** section for medium screens, but now the text is not properly vertically aligned in small screens (< 700px).
> 
> ![Screenshot_2020-02-28 The Next Web(2)](https://user-images.githubusercontent.com/16193212/75552506-351b0e00-5a15-11ea-8829-756e9ea387f9.png)
> 
> * [ ]  There is some unwanted between _Launch_ and _Distract_ on big screen sizes. Please fix it so they are aligned with the section above.
> 
> ![Screenshot_2020-02-28 The Next Web(7)](https://user-images.githubusercontent.com/16193212/75553421-1fa6e380-5a17-11ea-92e4-bf82b45579aa.png)
> 
> * [ ]  Currently, in the medium screen of the apps, gear, etc. (Please refer to the previous review)
> 
> ![Screenshot_2020-02-28 The Next Web(3)](https://user-images.githubusercontent.com/16193212/75552623-757a8c00-5a15-11ea-9eef-0efaf3ce86c4.png)
> 
> * [ ]  The latest deals align with 3 deals per row on medium screens and 1 per row on small screens. (Please refer to the last code review)
>   Your version:
>   ![Screenshot_2020-02-28 The Next Web(4)](https://user-images.githubusercontent.com/16193212/75552759-c38f8f80-5a15-11ea-843a-7423e6ad1992.png)
> 
> ![Screenshot_2020-02-28 The Next Web(5)](https://user-images.githubusercontent.com/16193212/75552836-f043a700-5a15-11ea-92bf-89ff598ce6a6.png)
> 
> Original site:
> ![Screenshot_2020-02-28 TNW - International technology news, business and culture(3)](https://user-images.githubusercontent.com/16193212/75552900-149f8380-5a16-11ea-9434-fe4f688b909e.png)
> ![Screenshot_2020-02-28 TNW - International technology news, business and culture(2)](https://user-images.githubusercontent.com/16193212/75552904-1701dd80-5a16-11ea-95c5-b1f79847cfde.png)
> 
> * [ ]  On scroll some of your page text is overlapping with the fixed navbar. Please fix it's  `z-index`.
>   ![Screenshot_2020-02-28 The Next Web(6)](https://user-images.githubusercontent.com/16193212/75553053-69db9500-5a16-11ea-957e-067cf52f1a68.png)
> 
> This project is one of the most demanding ones in the HTML path, in my personal opinion, so it's ok to take a bit more time with it. Try to rethink how you are organizing some of your HTML as it can help with positioning and responsibility.
> 
> **Please kindly fix the REQUIRED above issues and send another code review request.**
> 
> Cheers and Happy coding!👏👏👏
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

Thank you for your feedback @uryelah . Changes will be made following your feedback.

2020-03-02 07:41 UTC, addod19 requested changes
## Status: Require changes  🔴

Hi @Calvinoea, 👍 nice job fixing some of the changes requested by the previous reviewers. However, we still have some fixing to do. 🙂 Find comments below:
- Now the leftmost part of the row now has a width more than the 2/3 of the recommended width.  Consider using ```%```. For instance, the leftmost portion should be ```60%``` and rightmost ```30%``` that makes the leftmost 2/3 and rightmost 1/3 as recommended and the rest should be margin or possible play around with it. Kindly increase the size of the TNW logo. Currently, this is how it looks
![out](https://user-images.githubusercontent.com/46388113/75653187-e78ce400-5c54-11ea-81cf-6a4466daa0a0.PNG)
```Original version```
![out1](https://user-images.githubusercontent.com/46388113/75653237-0c815700-5c55-11ea-9aae-a5b736dba1c1.PNG)
- Kindly position, the articles properly on a small screen device. Currently, this is how it looks. 
The first article is out of position.
![out2](https://user-images.githubusercontent.com/46388113/75653620-dd1f1a00-5c55-11ea-9c22-f0c6df530e6a.PNG)
- Consider the width of the nav on a small screen device. Currently, this is how it looks
![out3](https://user-images.githubusercontent.com/46388113/75653793-27080000-5c56-11ea-8887-e78943ec6e2a.PNG)
```Original version```
![out4](https://user-images.githubusercontent.com/46388113/75653862-4acb4600-5c56-11ea-96ed-edd33cf7b12e.PNG)
- The latest funding section looks a bit messy. Let us check it out and fix it. Currently, this is how it looks. Some text is missing and articles overlap on each other.
![out5](https://user-images.githubusercontent.com/46388113/75654004-9978e000-5c56-11ea-9550-c10cffb8d283.PNG)
- Let us fix the latest deals section. Currently, this is how it looks, let us try to make it look like the original. Let us compare the 2 pictures below and see where it needs fixing.
```Our version```
![out6](https://user-images.githubusercontent.com/46388113/75654260-3a679b00-5c57-11ea-8725-ce113184ece0.PNG)
```Original version```
![out7](https://user-images.githubusercontent.com/46388113/75654293-4ce1d480-5c57-11ea-88fa-94361dd935c4.PNG)
- Let us fix the position of stackpath logo at the footer. Currently, this is how it looks on small screen
![out8](https://user-images.githubusercontent.com/46388113/75654427-9d593200-5c57-11ea-9757-95a62a258222.PNG)
```Original version```
![out9](https://user-images.githubusercontent.com/46388113/75654448-a77b3080-5c57-11ea-9292-df403d57e15b.PNG)
- In medium screen size, currently, this is how the footer looks
![ou](https://user-images.githubusercontent.com/46388113/75654583-f1fcad00-5c57-11ea-8005-603282f3b0cd.PNG)
```Original version```
![ou1](https://user-images.githubusercontent.com/46388113/75654605-fde86f00-5c57-11ea-9a53-6e3ca0c4da00.PNG)
- In the latest deals on a medium screen, let us fix the position of the articles and arrange them like the original. Currently, this is how it looks
![ou2](https://user-images.githubusercontent.com/46388113/75654747-56b80780-5c58-11ea-8bce-1ec2c08fe0a9.PNG)
```Original version```
![ou3](https://user-images.githubusercontent.com/46388113/75654772-5f104280-5c58-11ea-84e9-da04c88fdf00.PNG)
- Some articles overlap with others. Check image for reference
![ou4](https://user-images.githubusercontent.com/46388113/75654898-98e14900-5c58-11ea-96b2-7916bbe846af.PNG)
- Let us fix the positioning of the latest funding and how they are positioned
![ou6](https://user-images.githubusercontent.com/46388113/75655076-fffefd80-5c58-11ea-961a-b5a0d3620d7f.PNG)
```Original version```
![ou5](https://user-images.githubusercontent.com/46388113/75655090-0ab99280-5c59-11ea-9b42-5694a1eb2a18.PNG)

Kindly make these changes and submit another code review 👍 
Good luck with your next submission ✋ 
_Happy coding_ 💻 
Daniel Larbi Addo

2020-03-02 07:41 UTC, addod19 commented on styles.css
> +    /* min-width: 893px; */
Kindly delete all commented code as pointed out by the previous reviewers.

2020-03-02 08:19 UTC, Calvinoea commented
Thank you for your feedback @addod19 . I am working on the changes.

2020-03-02 15:32 UTC, nikasulo requested changes
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback :ok_hand:

2020-03-02 16:46 UTC, Oluwadamilareolusakin commented
# Great work @Calvinoea and @Mupa1 :clap: 
You have done nicely building this, however, I have noticed some serious issues with the responsiveness of your project and this being one of the most paramount requirements, I will be bringing it to your attention with a few screenshots I made. Please consider my comments below.

#### Responsiveness
One of the first issues I noticed is with the navigation bar, you have content overlapping it when you scroll, especially on mobile and tablet screen sizes(on desktop to, just a little less). There are also issues with section and element sizes, for instance, the first section on the page in both mobile and tablet screens have a number of visible bugs. Please consider the following screenshots, compare your project with the original on various screen sizes with the aid of the developer tools in the browser, make the necessary changes and request another review. 

I wish you the best and see you at the top!

2020-03-02 17:07 UTC, Calvinoea commented
> # Great work @Calvinoea and @Mupa1 👏
> You have done nicely building this, however, I have noticed some serious issues with the responsiveness of your project and this being one of the most paramount requirements, I will be bringing it to your attention with a few screenshots I made. Please consider my comments below.
> 
> #### Responsiveness
> One of the first issues I noticed is with the navigation bar, you have content overlapping it when you scroll, especially on mobile and tablet screen sizes(on desktop to, just a little less). There are also issues with section and element sizes, for instance, the first section on the page in both mobile and tablet screens have a number of visible bugs. Please consider the following screenshots, compare your project with the original on various screen sizes with the aid of the developer tools in the browser, make the necessary changes and request another review.
> 
> ![screenshot](https://camo.githubusercontent.com/1f912a86e5fbf1dedb4bf28d012114f50000efe1/68747470733a2f2f696d61676573322e696d67626f782e636f6d2f36322f35302f4a696c66726738565f6f2e676966)
> ![screenshot](https://camo.githubusercontent.com/cf600865d775f9a5298bbb6e5225a6f2fc315817/68747470733a2f2f696d61676573322e696d67626f782e636f6d2f64652f64302f657936616e5571325f6f2e676966)
> ![screenshot](https://camo.githubusercontent.com/95225f3dd9e483d946849b7fad923403f0bc6877/68747470733a2f2f696d61676573322e696d67626f782e636f6d2f65342f39382f646c3535775056375f6f2e676966)
> ![screenshot](https://camo.githubusercontent.com/a6acc6c1beec34bf8f540432f15d0f38ffa71386/68747470733a2f2f696d61676573322e696d67626f782e636f6d2f38382f61302f70676870524b63705f6f2e676966)
> 
> I wish you the best and see you at the top!
> 
> ##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

Thank you for your review @Oluwadamilareolusakin . I will make the necessary changes.

2020-03-02 20:36 UTC, nikasulo requested changes
# Hey team! :wave: 
Great work attempting to make changes to your project, I noticed a few things are different, however, many of the same problems I described and presented to you in the screenshots persist. Do you mind sending me a group message on Slack to discuss before your next review?

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

2020-03-03 04:57 UTC, Calvinoea commented
> # Hey team! 👋
> Great work attempting to make changes to your project, I noticed a few things are different, however, many of the same problems I described and presented to you in the screenshots persist. Do you mind sending me a group message on Slack to discuss before your next review?
> 
> ##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

Hello. I have sent you a message on Slack.

2020-03-03 09:18 UTC, rOluochKe requested changes
Hello Team!
### Good job so far and also on implementing changes from previous reviews. However, you still have some changes to work on before your project could be approved.
- Validate your html code and solve the errors, [use this website](https://validator.w3.org/#validate_by_upload)
![validator](https://user-images.githubusercontent.com/8114528/75760109-bfca7880-5d47-11ea-84b4-4b3676acc6e5.PNG)
- On mobile devices, some layout are off, make these changes
![mobile 2](https://user-images.githubusercontent.com/8114528/75760338-2d76a480-5d48-11ea-9360-9c8f20dcf87c.PNG)
![mobile 3](https://user-images.githubusercontent.com/8114528/75760342-2f406800-5d48-11ea-8857-9846d0bb31a4.PNG)
![mobile](https://user-images.githubusercontent.com/8114528/75760345-2fd8fe80-5d48-11ea-999c-a33946c1cc78.PNG)
### [REQUIRED]
- Your website is not responsive enough for both mobile and tablets, use the bootstrap grid to achieve this
- Avoid using br tag in your html code, rather you can achieve this via box model
![br](https://user-images.githubusercontent.com/8114528/75760698-bdb4e980-5d48-11ea-82ee-e88e90883ec8.PNG)
- Use html5 semantics tags like nav, section, article, main, aside where necessary, this will save you a lot of time.
### Make these changes and resubmit for another code review. Good luck.
- For assistance, reach out to me on slack @iamraymond
- Happy coding!

2020-03-03 10:18 UTC, Calvinoea commented
> Hello Team!
> 
> ### Good job so far and also on implementing changes from previous reviews. However, you still have some changes to work on before your project could be approved.
> * Validate your html code and solve the errors, [use this website](https://validator.w3.org/#validate_by_upload)
>   ![validator](https://user-images.githubusercontent.com/8114528/75760109-bfca7880-5d47-11ea-84b4-4b3676acc6e5.PNG)
> * On mobile devices, some layout are off, make these changes
>   ![mobile 2](https://user-images.githubusercontent.com/8114528/75760338-2d76a480-5d48-11ea-9360-9c8f20dcf87c.PNG)
>   ![mobile 3](https://user-images.githubusercontent.com/8114528/75760342-2f406800-5d48-11ea-8857-9846d0bb31a4.PNG)
>   ![mobile](https://user-images.githubusercontent.com/8114528/75760345-2fd8fe80-5d48-11ea-999c-a33946c1cc78.PNG)
> 
> ### [REQUIRED]
> * Your website is not responsive enough for both mobile and tablets, use the bootstrap grid to achieve this
> * Avoid using br tag in your html code, rather you can achieve this via box model
>   ![br](https://user-images.githubusercontent.com/8114528/75760698-bdb4e980-5d48-11ea-82ee-e88e90883ec8.PNG)
> * Use html5 semantics tags like nav, section, article, main, aside where necessary, this will save you a lot of time.
> 
> ### Make these changes and resubmit for another code review. Good luck.
> * For assistance, reach out to me on slack @IAmRaymond
> * Happy coding!

Thank you, @rOluochKe . I am making the changes.

2020-03-09 23:45 UTC, uryelah commented
Hello **Calvin Ebun-Amu** & **Mupa Nzaphila**, I'm Sarah, your reviewer for this PR 👩‍🚀  

Good job fixing some of the bugs from the past reviews, but I noticed that there still a lot of the layout is breaking, and some new bugs also appeared, though the project is way better since the first time I reviewed it.

If you need more assistance please reach out via Slack and we can have a call to check how to approach these fixes.

This is one of the most complex projects of the HTML path, so it's ok if you take some time to rework the markup so that it's easier to style and align.

--------

### Required changes 🛠 

- [ ] Please fix the articles of the site that are overlapping on medium to small screens:
![Screenshot_2020-03-09 The Next Web(5)](https://user-images.githubusercontent.com/16193212/76266305-c5432980-6245-11ea-8880-41e4321c9349.png)
![Screenshot_2020-03-09 The Next Web(1)](https://user-images.githubusercontent.com/16193212/76266312-c6745680-6245-11ea-8aaf-ac729c9cb19f.png)
![Screenshot_2020-03-09 The Next Web](https://user-images.githubusercontent.com/16193212/76266313-c7a58380-6245-11ea-8e81-c695434f4b87.png)
![Screenshot_2020-03-09 The Next Web(6)](https://user-images.githubusercontent.com/16193212/76266298-c3796600-6245-11ea-9b7b-cd930cc33fc0.png)

- [ ] The text of the three main articles should at the bottom of the image, with the gradient behind it.
![Screenshot_2020-03-09 The Next Web(2)](https://user-images.githubusercontent.com/16193212/76266555-a002eb00-6246-11ea-96a3-2d924757dbb6.png)


- [ ] Please fix the text and nav area for small screens:
![Screenshot_2020-03-09 The Next Web(3)](https://user-images.githubusercontent.com/16193212/76266309-c5dbc000-6245-11ea-9a40-0fc610322ade.png)




---------


**Please fix the required changes 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-10 07:44 UTC, Calvinoea commented
> Hello **Calvin Ebun-Amu** & **Mupa Nzaphila**, I'm Sarah, your reviewer for this PR 👩‍🚀
> 
> Good job fixing some of the bugs from the past reviews, but I noticed that there still a lot of the layout is breaking, and some new bugs also appeared, though the project is way better since the first time I reviewed it.
> 
> If you need more assistance please reach out viahttps://microverse.zendesk.com/hc/en-us/articles/360026625973-How-can-I-get-help-from-TSEs-
> 
> This is one of the most complex projects of the HTML path, so it's ok if you take some time to rework the markup so that it's easier to style and align.
> 
> ### Required changes 🛠
> * [ ]  Please fix the articles of the site that are overlapping on medium to small screens:
>   ![Screenshot_2020-03-09 The Next Web(5)](https://user-images.githubusercontent.com/16193212/76266305-c5432980-6245-11ea-8880-41e4321c9349.png)
>   ![Screenshot_2020-03-09 The Next Web(1)](https://user-images.githubusercontent.com/16193212/76266312-c6745680-6245-11ea-8aaf-ac729c9cb19f.png)
>   ![Screenshot_2020-03-09 The Next Web](https://user-images.githubusercontent.com/16193212/76266313-c7a58380-6245-11ea-8e81-c695434f4b87.png)
>   ![Screenshot_2020-03-09 The Next Web(6)](https://user-images.githubusercontent.com/16193212/76266298-c3796600-6245-11ea-9b7b-cd930cc33fc0.png)
> * [ ]  The text of the three main articles should at the bottom of the image, with the gradient behind it.
>   ![Screenshot_2020-03-09 The Next Web(2)](https://user-images.githubusercontent.com/16193212/76266555-a002eb00-6246-11ea-96a3-2d924757dbb6.png)
> * [ ]  Please fix the text and nav area for small screens:
>   ![Screenshot_2020-03-09 The Next Web(3)](https://user-images.githubusercontent.com/16193212/76266309-c5dbc000-6245-11ea-9a40-0fc610322ade.png)
> 
> **Please fix the required changes 👷 before asking for a new code review**
> 
> Cheers and Happy coding!👏👏👏
> 
> Code review by **Sarah Uryelah Silva Chamorro**
> 
> (Feel free to contact me on slack by the handle of **sarah** if you have any additional question)

Hey @uryelah . Thank you for the points of correction. I am currently working on making the changes.

2020-03-10 11:13 UTC, rOluochKe requested changes
Hello @Calvinoea  and @Mupa1 
### You have really tried and for also trying to make the changes from previous reviews. :clap: However, there are a few issues you need to implement before your project could be approved.
- Validate your html code and resolve the issues, [use this tool](https://validator.w3.org/#validate_by_upload)
![not responsive 2](https://user-images.githubusercontent.com/8114528/76307025-0df7f280-62d9-11ea-9ea7-d51081099bfc.PNG)
![validator](https://user-images.githubusercontent.com/8114528/76307026-0fc1b600-62d9-11ea-879a-57310acc235b.PNG)
![not responsive 3](https://user-images.githubusercontent.com/8114528/76307029-118b7980-62d9-11ea-8454-a0c2baacf942.PNG)
![not responsive](https://user-images.githubusercontent.com/8114528/76307037-15b79700-62d9-11ea-8575-9d895d0a942e.PNG)
- You need to put more work responsive design to achieve the desired layout for both phones and medium screens devices
![not responsive 1](https://user-images.githubusercontent.com/8114528/76307017-09cbd500-62d9-11ea-974d-790e041e8955.PNG)
### Make these changes and resubmit for another code review, good luck.
- You can also reach out to any TSE to help you if you are facing challenges, it is good to ask for help.
- You can contact me on slack @iamraymond
- Happy coding

2020-03-10 13:30 UTC, rOluochKe requested changes
Hello Team!
### Still not looking good, do you mind seeking help from either your mentors or any TSE
![not looking good](https://user-images.githubusercontent.com/8114528/76316922-5cfb5300-62ec-11ea-9ab2-bd64fa8312a0.PNG)
![res 2](https://user-images.githubusercontent.com/8114528/76316929-5ec51680-62ec-11ea-9528-cc1879932c91.PNG)
![res 3](https://user-images.githubusercontent.com/8114528/76316934-5ff64380-62ec-11ea-85ad-b833e42a28aa.PNG)

### You can contact me as well on slack @iamraymond

2020-03-11 09:14 UTC, rOluochKe requested changes
Hello @Calvinoea and @Mupa1 
### Good job :clap: I see improvements but still not yet there, a few issues to work on.
- Concentrate mostly on the responsive design sizes medium: min-width around 768px
large: min-width 1024px
![not good 2](https://user-images.githubusercontent.com/8114528/76400542-8c17d000-6391-11ea-9d5e-d9e0aa4adf7a.PNG)
![not good](https://user-images.githubusercontent.com/8114528/76400549-8fab5700-6391-11ea-830f-e193cebc741e.PNG)
### Implement the changes and resubmit for another code review. Good luck
- Happy coding.

2020-03-11 10:07 UTC, Calvinoea commented
> Hello @Calvinoea and @Mupa1
> 
> ### Good job 👏 I see improvements but still not yet there, a few issues to work on.
> * Concentrate mostly on the responsive design sizes medium: min-width around 768px
>   large: min-width 1024px
>   ![not good 2](https://user-images.githubusercontent.com/8114528/76400542-8c17d000-6391-11ea-9d5e-d9e0aa4adf7a.PNG)
>   ![not good](https://user-images.githubusercontent.com/8114528/76400549-8fab5700-6391-11ea-830f-e193cebc741e.PNG)
> 
> ### Implement the changes and resubmit for another code review. Good luck
> * Happy coding.

Thank you @rOluochKe . I am currently making the changes.

2020-03-18 22:18 UTC, pelzolga123 requested changes
Project requires changes.

2020-03-18 22:18 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
### You made some changes, but still a lot is messed up:
* Laptop version
![image](https://user-images.githubusercontent.com/20416431/77012392-8ebc8b80-6976-11ea-815f-23daa1563c3e.png)
Original:
![image](https://user-images.githubusercontent.com/20416431/77012564-d8a57180-6976-11ea-86cc-c7673e70e200.png)

* Tablet version
![image](https://user-images.githubusercontent.com/20416431/77012283-5c129300-6976-11ea-8ac6-297143e84465.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/77012584-e8bd5100-6976-11ea-9b3d-41c0f66afb48.png)

* Mobile version
![image](https://user-images.githubusercontent.com/20416431/77012306-67fe5500-6976-11ea-9f51-6fba03b6ca57.png)

Original:
![image](https://user-images.githubusercontent.com/20416431/77012615-f4107c80-6976-11ea-85d4-7b2263706ae1.png)

### Please take a good look at original website. Your project should look like original. And only after your project looks like original, send another review request. 

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-03-20 10:17 UTC, lekegitrepo commented
### Hi @Calvinoea and @Mupa1 
### I would suggest that you should take some time to learn more about responsive web design before continue working on this project.

### The changes required from the last review is not met.

### you can contact me on slack if you have any doubt or question.

### Reviewed by: Temitayo Adeleke

2020-03-20 10:20 UTC, lekegitrepo requested changes
### Status: Require changes.

2020-03-23 23:35 UTC, uryelah commented
## Calvin! You did it! 👏 👏 👏 

You've come a long way since the start of this project. Everything is responsive and neat.

There are some small issues here and there but the main structure is working and you should be really proud of yourself for achieving this!

## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

### Optional Improvement

- [ ] The logo has some white margin already it and it's not scaling correctly. Consider fixing it and maybe using an `svg` instead of an image for it.
![Screenshot_2020-03-23 The Next Web](https://user-images.githubusercontent.com/16193212/77373001-cb590000-6d45-11ea-8f26-d2cf6e4ac599.png)


-------

**Keep being an awesome dev, good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-24 05:53 UTC, merged